### ISSUE TITLE
Gist could not be found.

### ISSUE THREAD

**Issue by andrew-dixon** [stevewithington/MuraGist#2]
@stevewithington - I'm trying to use the Gist plugin and no matter what I do I'm getting the following error:

Gist #0b56955b84b744cde58b could not be found. Maybe it no longer exists, or the Gist service is currently unavailable.

I've checked all the settings, regenerated the personal key several times, reset the application in Mura, etc., etc... and nothing seems to work. The gist exists and is publically available:

https://gist.github.com/andrew-dixon/0b56955b84b744cde58b

Any ideas? Is it not compatible with 6.2?

Thanks

Andrew.

**Comment by andrew-dixon** [comment]
Think this must be some sort of firewall issue or something on AWS, as I've just pulled the bundle from my live server to my development machine and it works fine, any ideas why this might be? Does it connect to Github on a specific port and/or protocol?

**Comment by stevewithington** [comment]
@andrew-dixon sorry, the plugin works with 6.2 for me. What's your environment setup?

**Comment by stevewithington** [comment]
@andrew-dixon I think I know what your issue is. Are you attempting to use the Display Gist display object, and you're passing in a Gist Filename? If so, try removing the Gist Filename.

The issue is, that if you pass in a Gist Filename, that filename MUST exist in the Gist ... because Gists can have more than one file associated with it. So, it just can't locate it.

Please let me know if this is your issue.

**Comment by stevewithington** [comment]
Also, I just tested with the Gist you provided, and worked fine for me in 6.2. Here's my configurator screen:
![screen shot 2015-03-04 at 14 53 21](https://cloud.githubusercontent.com/assets/251648/6493136/4f2aacda-c27e-11e4-9d34-d1046912d19d.png)

**Comment by andrew-dixon** [comment]
@stevewithington - I'm inserting the Gist into the content area using the Mura tag in the following way:

[mura]$.dspGist(gistID='0b56955b84b744cde58b')[/mura]

I'm not using the filename.

I've also tried using the display object as you show above and that doesn't work either. 

My environment is:

Core Version 6.2.6187
Site Version 6.2.6187
App Server Lucee (4.5.1.000)
DB Server MySQL (5.5.41-log)
Java Version 1.7.0_75
OS Version Linux (3.14.33-26.47.amzn1.x86_64)

I really not sure what is going on here, clearing I'm doing something wrong but I really can't see what it is. At first I thought it was an AWS issue but I'm getting the same from my local dev machine as well.

**Comment by stevewithington** [comment]
Did you enter your Github account username and create a Personal Access Token?

**Comment by stevewithington** [comment]
Can you try manually updating the gistGateway.cfc to this:
https://github.com/stevewithington/MuraGist/blob/42328316f52de6cafec6beacf405ef9b69b2c8bd/extensions/lib/gist/gistGateway.cfc

I ran into some odd issue today trying to replicate this, and maybe this will help.

**Comment by andrew-dixon** [comment]
@stevewithington - I updated the file and reloaded the Mura but still the same thing. I've also just try deleting the existing the Github Personal Access Token and creating a new old and updating to that but nothing as well. On Github the Personal Access Token says "Never Used" next to it:

![screen shot 2015-03-05 at 08 35 49 1](https://cloud.githubusercontent.com/assets/7441801/6501642/f4c4b78c-c312-11e4-99ac-b612c2a7a72e.png)

**Comment by stevewithington** [comment]
@andrew-dixon well, something odd is going on. Try deleting the plugin, and download my latest version to try again. I'm using a very similar environment (Lucee, MySQL, Mura 6.2, Java 7 on OSX).

Maybe try the display object via the UI as well, and leave the filename blank like you did before.

Otherwise, what does this return for you:
`<script src="https://gist.github.com/0b56955b84b744cde58b.js"></script>`

Because, that's essentially, all that's it returning when you call `$.dspGist(gistID='0b56955b84b744cde58b')`

**Comment by andrew-dixon** [comment]
@stevewithington - Thanks for trying to help with this but I really can't get to working, it is so odd. I have tried removing and re-adding it several times. If I use the Gist embed code directly from Github it works fine. For now I will leave it. If you're at dev.objective in May maybe I can grab five minutes of your time and you can show me what I'm doing wrong, I'm sure it is something stupid!!!
